### ISSUE TITLE
Add the ability to see an interface simplifyed when you are connected as a guest

### ISSUE THREAD

**Issue by tamaraaPrs** [polypoly-team/android-app#104]
This simplified menu contains:

- Settings
- Rules of the game
- Possibility to visit the map
- Return to sign In button

**Comment by SolalPirelli** [comment]
What will this simplified interface contain?

**Comment by tamaraaPrs** [comment]
@SolalPirelli It is also part of my task to see what could be done with the interface without the user being logged in. For example the rules, or the setting could be in the simplified interface. It is also possible to imagine that more complex things like some parts of the profile can be done but I have to find a good balance between spending a reasonable amount of time on this task and doing something nice.

**Comment by SolalPirelli** [comment]
> I have to find a good balance between spending a reasonable amount of time on this task and doing something nice.

Exactly :) one way to do this would be to time-box the "exploration" part to, say, 30min, and then write down what you'll do in the remainder of the task and discuss with the team
