### ISSUE TITLE
Link the profile-related activities with Firebase

### ISSUE THREAD

**Issue by Jharaxus** [polypoly-team/android-app#26]
Link profile related activities with Firebase to update the database when the front-end is updated
Creating a group pushes a new Group object in the DB: Issue [#28](https://github.com/polypoly-team/android-app/issues/28)

**Comment by Jharaxus** [comment]
Link profile related activities with Firebase
- [ ] Issue [#28](https://github.com/polypoly-team/android-app/issues/28)
- [ ] Issue [#29](https://github.com/polypoly-team/android-app/issues/29)
- [ ] Issue [#30](https://github.com/polypoly-team/android-app/issues/30)

**Comment by Jharaxus** [comment]
The behavior works but test fail

**Comment by AlSchlo** [comment]
What PR is this in?

**Comment by vrooomer** [comment]
Done in sprint 3, some testing bugs but they are part of a new issue #93
