### ISSUE TITLE
Refactor magic numbers in Activities

### ISSUE THREAD

**Issue by Jharaxus** [polypoly-team/android-app#40]
Some magic numbers sometimes appear in the codes of Activities, however, such as pointed [here](https://github.com/polypoly-team/android-app/pull/23#discussion_r1140305979), that doesn't make much sense when read out of context (as it just looks like any magic number --> why does it have this value?).

Therefore, it could be a good improve to our codebase to cross-read all activities' code and look:
- Wether some magic values constants could be merged together and put them in separate UI config files
- For the others, find some way to make them clearer such as turning them into constants located in their activity’s companion object.

**Comment by Kaz-ookid** [comment]
we should adress this issue soon, and create a Constants class in utils/
