### ISSUE TITLE
Create a communication diagram for DB

### ISSUE THREAD

**Issue by vrooomer** [polypoly-team/android-app#69]
This isn't directly code, but I'll do a diagram so that we all agree in the way the Game communicates with the Players via the DB

**Comment by Kaz-ookid** [comment]
final DB schema is here :

https://lucid.app/lucidchart/9118f492-ee01-451e-bd79-d077ba875713/edit?viewport_loc=-403%2C-45%2C2425%2C1178%2C0_0&invitationId=inv_b8f891fe-5a98-4c9c-af7d-710150661d0e

(done by Victor and Tamara, thanks!)
