### ISSUE TITLE
JSON Firebase

### ISSUE THREAD

**Issue by vrooomer** [polypoly-team/android-app#81]
As mentionned in #80, we should find a solution to that JSON that keeps forcing us to change our project file sometimes

**Comment by Kaz-ookid** [comment]
google-services.json changes as we enter new SHA1 footprints to the project, or when we change specific settings. I have added every one's key once and for all yesterday, so we should not need to update it any soon.
I think that the only solution would be to find a way to be able to change it in the main code without needing to create a PR for it, and to wait for an aprovement, but the fact that this changement will be rare enough yet, we may also juste keep it as it is :)
