### ISSUE TITLE
Location(or Building, or Property) naming

### ISSUE THREAD

**Issue by AmLibra** [polypoly-team/android-app#83]
As mentioned in my pull request this week, the name Location might not be well suited for the MapActivity class, which requires us to juggle with the Location from OSM used to locate the phone user, and Location that is used as a part of the game.

The name that would better suit Monopoly would be Property. This would allow us to differentiate the two classes without adding the import prefix each time, and to remain more faithful to the original game.

**Comment by jadtl** [comment]
I'm concerned that "property" would collide with the term "property" as in "attribute", even though it hasn't been used in our codebase yet. Maybe "building" is a safer choice? It's also more descriptive in our case.
