### ISSUE TITLE
Technical debt in MapActivity.kt

### ISSUE THREAD

**Issue by AmLibra** [polypoly-team/android-app#84]
As mentioned in this week's PR, the MapActivity class is getting way too large, and I propose the following changes:
- Move more of the backend stuff and data storing to the MapViewModel Class, such as the list of visible "Locations" (see issue 83) and the logic to roll dice.
- Add a class to contain all the low level UI Composable components, leaving only the top-level descriptions in MapActivity, as they are required for the UX and game logic. Another solution for Composable functions would be to create different files for each UI element, e.g. MapView.kt, BuildingInfoUIComponent.kt, and Hud.kt.

**Comment by SolalPirelli** [comment]
Can you frame this in a way that helps users as well? Are there features that are currently too hard to build / too buggy / ... as a result of this debt?
