### ISSUE TITLE
Create a dummie version of LobbyActivity that links to Map/GameActivity.kt

### ISSUE THREAD

**Issue by vrooomer** [polypoly-team/android-app#98]

**Comment by SolalPirelli** [comment]
What's the goal of this task given that there's also one for the real lobby?

**Comment by vrooomer** [comment]
The time counted also includes all the deleted work of the last try to make a `GameLobbyActivity`. This task is very important so we finally can have access to the `MapActivity`. Of course now that this is merged, we can continue to implement the final activity
